my_blog/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove,
                                     name='cart_remove'),
]

my_blog/firstblog/urls.py
from django.urls import path
from . import views
from .feeds import LastestPostFeed

app_name="firstblog"

urlpatterns=[
    path('',views.post_list,name='post_list'),
    path('tag/<slug:tag_slug>/',views.post_list,
                        name='post_list_by_tag'),
    #path('',views.PostListView.as_view(),name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/'
         ,views.post_detail,name="post_detail"),
    path('<int:post_id>/share/',
         views.post_share, name='post_share'),
    path('<int:post_id>/comment/',
         views.post_comment, name='post_comment'),
     
    path('feed/', LastestPostFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
]

my_blog/my_blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from firstblog.views import home
#from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.sitemaps.views import sitemap
from firstblog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('firstblog.urls',namespace='blog')),
    path('account/', include('account.urls',namespace='account')),
    path('', home),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
           name='django.contrib.sitemaps.views.sitemap'),
    path('images/', include('images.urls',namespace='images')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

my_blog/firstblog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset()\
                      .filter(status=Post.Status.published)
    

class Post(models.Model):
    
    class Status(models.TextChoices):
        draft='df','draft'
        published='pb','published'
    
    title=models.CharField(max_length=250)
    slug=models.SlugField(max_length=250,
                          unique_for_date='publish')
    author=models.ForeignKey(User,
                             on_delete=models.CASCADE,
                             related_name='blog_posts')
    body=models.TextField()
    publish=models.DateTimeField(default=timezone.now)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    status=models.CharField(max_length=2,
                            choices=Status.choices,
                            default=Status.draft)
    objects=models.Manager()
    published=PublishedManager()
    tags=TaggableManager()

    class Meta:
        ordering=['-publish']
        indexes=[
           models.Index(fields=['-publish'])
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                        args=[self.publish.year,
                              self.publish.month,
                              self.publish.day,
                              self.slug])

class Comment(models.Model):
    post=models.ForeignKey(Post,
                         on_delete=models.CASCADE,
                         related_name='comments')
    name=models.CharField(max_length=80)
    email=models.EmailField()
    body=models.TextField()
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    active=models.BooleanField(default=True)

    class Meta:
        ordering=['created']
        indexes=[
            models.Index(fields=['created']),
        ]
    def __str__(self):
        return f'comment by {self.name} on {self.post}'

my_blog/firstblog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name=forms.CharField(max_length=25)
    email=forms.EmailField()
    to=forms.EmailField()
    comments=forms.CharField(required=False,
                             widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=['name','email','body']

    #def __init__(self, *args, **kwargs):
        #super(CommentForm, self).__init__(*args, **kwargs)
        
        # Make first name, last name, and email fields read-only
        #self.fields['name'].widget.attrs['readonly'] = True
        #self.fields['last_name'].widget.attrs['readonly'] = True
        #self.fields['email'].widget.attrs['readonly'] = True

class SearchForm(forms.Form):
    query = forms.CharField()
    

my_blog/firstblog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post , Comment
from django.http import Http404
from django.core.paginator import Paginator,EmptyPage,\
                                  PageNotAnInteger
from django.views.generic import ListView
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank, TrigramSimilarity
from .forms import EmailPostForm , CommentForm, SearchForm
from django.core.mail import send_mail
from django.views.decorators.http import require_POST
from taggit.models import Tag
from django.db.models import Count
from django.contrib.auth.decorators import login_required


def post_list(request, tag_slug=None):
    post_list=Post.published.all()
    tag =None
    if tag_slug:
        tag=get_object_or_404(Tag, slug=tag_slug)
        post_list= post_list.filter(tags__in=[tag])
    ##paigination with 3 posts per page
    paginator=Paginator(post_list, 3)
    page_number=request.GET.get('page', 1)
    try:
        posts=paginator.page(page_number)
    except PageNotAnInteger:
        posts=paginator.page(1)
    except EmptyPage:
        ##if page_number isnt exist deliver last page
        posts=paginator.page(paginator.num_pages)

    return render(request,
                  'firstblog/post/list.html',
                  {'posts':posts,
                   'tag':tag})

#class PostListView(ListView):
    #queryset=Post.published.all()
    #context_object_name='posts'
    #paginate_by=3
    #template_name='firstblog/post/list.html'

def post_detail(request, year, month, day, post):
    #try:
        #post=Post.published.get(id=id)
    #except Post.DoesNotExist:
        #raise Http404("No post found.")
    post=get_object_or_404(Post,
                           status=Post.Status.published,
                           slug=post,
                           publish__year=year,
                           publish__month=month,
                           publish__day=day)
    
    comments=post.comments.filter(active=True)
    form=CommentForm()

    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in = post_tags_ids)\
                                          .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
                                 .order_by('-same_tags','-publish')[:4]

    return render(request,
                  'firstblog/post/detail.html',
                  {'post':post,
                   'comments':comments,
                   'form':form,
                   'similar_posts':similar_posts})

@login_required
def post_share(request, post_id):
    post=get_object_or_404(Post, id=post_id, status=Post.Status.published)
    sent = False

    if request.method == 'POST':
        form=EmailPostForm(request.POST)
        if form.is_valid():
            cd=form.cleaned_data
            post_url = request.build_absolute_uri(
                       post.get_absolute_url())
            subject = f"{cd['name']} recommends you read "\
                      f"{post.title}"
            message = f"Read {post.title} at {post_url}\n\n"\
                      f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'nooshinghobadi0@gmail.com',
                      [cd['to']])
            sent = True
    else:
        form=EmailPostForm()
    return render(request, 'firstblog/post/share.html',
                            {'post':post,'form':form,'sent': sent})

@login_required
def post_comment(request, post_id):
    post=get_object_or_404(Post, id=post_id, status=Post.Status.published)
    comment=None
    if request.method == 'POST': 
        form=CommentForm(request.POST)
        if form.is_valid():
            comment=form.save(commit=False)
            comment.post=post
            comment.save()
    #age request get bashe va fard id post ra bedanad ejra mishe
    else:
        if request.user.is_authenticated:
            initial_data = {
                'name': request.user.first_name,
                #'last_name': request.user.last_name,
                'email': request.user.email,
            }
            form = CommentForm(initial=initial_data)
        else:
            pass
    return render(request, 'firstblog/post/comment.html',
                  {'post':post,
                  'form':form,
                  'comment':comment})

def home(request):
    return render(request,'home/home.html')

def post_search(request):
    form = SearchForm()
    query = None
    results = []

    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', weight = 'A') + SearchVector('body', weight = 'B')
            search_query = SearchQuery(query)
            results = Post.published.annotate(
                similarity = TrigramSimilarity('title', query),
            ).filter(similarity__gte = 0.1).order_by('-similarity')
    return render(request,
                    'firstblog/post/search.html',
                    {'form': form,
                    'query': query,
                    'results': results})

my_blog/firstblog/templates/firstblog/post/comment.html
{% extends "firstblog/base.html" %}

{% block title %}add a comment{% endblock %}

{% block content %}
  {% if comment %}
    <h2>your comment has been added.</h2>
     <p><a href="{{ post.get_absolute_url }}">back to the post</a></p>
  {% else %}
    {% include "firstblog/post/includes/comment_form.html" %}
  {% endif %}
{% endblock %}

my_blog/firstblog/templates/firstblog/post/detail.html
{% extends "firstblog/base.html" %}
{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
  <h1>{{ post.title }}</h1>
    <p class="date">
        published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|markdown }}
    <p>
      <a href="{% url "blog:post_share" post.id %}">
        share this post
      </a>
    </p>

    <h2>Similar posts</h2>
    {% for post in similar_posts %}
      <p>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
      </p>
    {% empty %}
      There are no similar posts yet.
    {% endfor %}

    {% with comments.count as total_comments %}
      <h2>
        {{ total_comments }} comment {{ total_comments|pluralize }}
      </h2>
    {% endwith %}
    {% for comment in comments %}
      <div class="comment">
        <p class="info">
          Comment {{ forloop.counter }} by {{ comment.name }}
          {{ comment.created }}
        </p>
        {{ comment.body|linebreaks }}
      </div>
    {% empty %}
      <p>there are no comments.</p>
    {% endfor %}
    {% include "firstblog/post/includes/comment_form.html" %}
{% endblock %}

my_blog/firstblog/templates/firstblog/post/lastest_posts.html
<ul>
    {% for post in lastest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

my_blog/firstblog/templates/firstblog/post/list.html
{% extends "firstblog/base.html" %}
{% load blog_tags %}

{% block title %}my blog{% endblock %}

{% block content %}
  {% if tag %}
    <h2>Posts tagged with "{{ tag.name }}"</h2>
  {% endif %}
  {% for post in posts %}
    <h5 class="card-title">{{ post.title }}</h5>
    <h2>
        <a href="{{ post.get_absolute_url }}"class="btn btn-primary">Read More</a>
    </h2>
    <p class="tags">
      Tags:
      {% for tag in post.tags.all %}
        <a href="{% url "blog:post_list_by_tag" tag.slug %}">
          {{ tag.name }}
        </a>
        {% if not forloop.last %}, {% endif %}
      {% endfor %}
    </p>
    <p class="date">
        published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|markdown|truncatewords:30 }}
  {% endfor %}
  {% include "pagination.html" with page=posts %}
{% endblock %}

my_blog/firstblog/templates/firstblog/post/search.html
{% extends "firstblog/base.html" %}
{% load blog_tags %}

{% block title %}Search{% endblock %}

{% block content %}
  {% if query %}
    <h1>Posts containing "{{ query }}"</h1>
    <h3>
        {% with results.count as total_results %}
            Found {{ total_results }} result{{ total_results|pluralize }}
        {% endwith %}
    </h3>
    {% for post in results %}
      <h4>
         <a href="{{ post.get_absolute_url }}"class="btn btn-primary">
              {{ post.title }}
         </a>
     </h4>
     {{ post.body|markdown|truncatewords_html:12 }}
    {% empty %}
      <p>There are no results for your query.</p>
    {% endfor %}
    <p><a href="{% url "blog:post_search" %}">Search again</a></p>
  {% else %}
    <h1>Search for posts</h1>
    <form method="get">
        {{ form.as_p }}
        <input type="submit" value="Search">
    </form>
  {% endif %}
{% endblock %}

my_blog/firstblog/templates/firstblog/post/share.html
{% extends "firstblog/base.html" %}

{% block title %}share a post{% endblock %}

{% block content %}
  {% if sent %}
    <h1>E-mail successfully sent</h1>
     <p>
        "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
     </p>
  {% else %}
    <h1>share "{{ post.title }}" by e-mail</h1>
    <form method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Send e-mail">
    </form>
  {% endif %}
{% endblock %}