my_blog/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove,
                                     name='cart_remove'),
]

my_blog/firstblog/urls.py
from django.urls import path
from . import views
from .feeds import LastestPostFeed

app_name="firstblog"

urlpatterns=[
    path('',views.post_list,name='post_list'),
    path('tag/<slug:tag_slug>/',views.post_list,
                        name='post_list_by_tag'),
    #path('',views.PostListView.as_view(),name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/'
         ,views.post_detail,name="post_detail"),
    path('<int:post_id>/share/',
         views.post_share, name='post_share'),
    path('<int:post_id>/comment/',
         views.post_comment, name='post_comment'),
     
    path('feed/', LastestPostFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
]

my_blog/my_blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from firstblog.views import home
#from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.sitemaps.views import sitemap
from firstblog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('firstblog.urls',namespace='blog')),
    path('account/', include('account.urls',namespace='account')),
    path('', home),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
           name='django.contrib.sitemaps.views.sitemap'),
    path('images/', include('images.urls',namespace='images')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

my_blog/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list,
         name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail,
         name='product_detail'),
]

my_blog/firstblog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset()\
                      .filter(status=Post.Status.published)
    

class Post(models.Model):
    
    class Status(models.TextChoices):
        draft='df','draft'
        published='pb','published'
    
    title=models.CharField(max_length=250)
    slug=models.SlugField(max_length=250,
                          unique_for_date='publish')
    author=models.ForeignKey(User,
                             on_delete=models.CASCADE,
                             related_name='blog_posts')
    body=models.TextField()
    publish=models.DateTimeField(default=timezone.now)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    status=models.CharField(max_length=2,
                            choices=Status.choices,
                            default=Status.draft)
    objects=models.Manager()
    published=PublishedManager()
    tags=TaggableManager()

    class Meta:
        ordering=['-publish']
        indexes=[
           models.Index(fields=['-publish'])
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                        args=[self.publish.year,
                              self.publish.month,
                              self.publish.day,
                              self.slug])

class Comment(models.Model):
    post=models.ForeignKey(Post,
                         on_delete=models.CASCADE,
                         related_name='comments')
    name=models.CharField(max_length=80)
    email=models.EmailField()
    body=models.TextField()
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    active=models.BooleanField(default=True)

    class Meta:
        ordering=['created']
        indexes=[
            models.Index(fields=['created']),
        ]
    def __str__(self):
        return f'comment by {self.name} on {self.post}'

my_blog/firstblog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name=forms.CharField(max_length=25)
    email=forms.EmailField()
    to=forms.EmailField()
    comments=forms.CharField(required=False,
                             widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=['name','email','body']

    #def __init__(self, *args, **kwargs):
        #super(CommentForm, self).__init__(*args, **kwargs)
        
        # Make first name, last name, and email fields read-only
        #self.fields['name'].widget.attrs['readonly'] = True
        #self.fields['last_name'].widget.attrs['readonly'] = True
        #self.fields['email'].widget.attrs['readonly'] = True

class SearchForm(forms.Form):
    query = forms.CharField()
    

my_blog/firstblog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post , Comment
from django.http import Http404
from django.core.paginator import Paginator,EmptyPage,\
                                  PageNotAnInteger
from django.views.generic import ListView
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank, TrigramSimilarity
from .forms import EmailPostForm , CommentForm, SearchForm
from django.core.mail import send_mail
from django.views.decorators.http import require_POST
from taggit.models import Tag
from django.db.models import Count
from django.contrib.auth.decorators import login_required


def post_list(request, tag_slug=None):
    post_list=Post.published.all()
    tag =None
    if tag_slug:
        tag=get_object_or_404(Tag, slug=tag_slug)
        post_list= post_list.filter(tags__in=[tag])
    ##paigination with 3 posts per page
    paginator=Paginator(post_list, 3)
    page_number=request.GET.get('page', 1)
    try:
        posts=paginator.page(page_number)
    except PageNotAnInteger:
        posts=paginator.page(1)
    except EmptyPage:
        ##if page_number isnt exist deliver last page
        posts=paginator.page(paginator.num_pages)

    return render(request,
                  'firstblog/post/list.html',
                  {'posts':posts,
                   'tag':tag})

#class PostListView(ListView):
    #queryset=Post.published.all()
    #context_object_name='posts'
    #paginate_by=3
    #template_name='firstblog/post/list.html'

def post_detail(request, year, month, day, post):
    #try:
        #post=Post.published.get(id=id)
    #except Post.DoesNotExist:
        #raise Http404("No post found.")
    post=get_object_or_404(Post,
                           status=Post.Status.published,
                           slug=post,
                           publish__year=year,
                           publish__month=month,
                           publish__day=day)
    
    comments=post.comments.filter(active=True)
    form=CommentForm()

    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in = post_tags_ids)\
                                          .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
                                 .order_by('-same_tags','-publish')[:4]

    return render(request,
                  'firstblog/post/detail.html',
                  {'post':post,
                   'comments':comments,
                   'form':form,
                   'similar_posts':similar_posts})

@login_required
def post_share(request, post_id):
    post=get_object_or_404(Post, id=post_id, status=Post.Status.published)
    sent = False

    if request.method == 'POST':
        form=EmailPostForm(request.POST)
        if form.is_valid():
            cd=form.cleaned_data
            post_url = request.build_absolute_uri(
                       post.get_absolute_url())
            subject = f"{cd['name']} recommends you read "\
                      f"{post.title}"
            message = f"Read {post.title} at {post_url}\n\n"\
                      f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'nooshinghobadi0@gmail.com',
                      [cd['to']])
            sent = True
    else:
        form=EmailPostForm()
    return render(request, 'firstblog/post/share.html',
                            {'post':post,'form':form,'sent': sent})

@login_required
def post_comment(request, post_id):
    post=get_object_or_404(Post, id=post_id, status=Post.Status.published)
    comment=None
    if request.method == 'POST': 
        form=CommentForm(request.POST)
        if form.is_valid():
            comment=form.save(commit=False)
            comment.post=post
            comment.save()
    #age request get bashe va fard id post ra bedanad ejra mishe
    else:
        if request.user.is_authenticated:
            initial_data = {
                'name': request.user.first_name,
                #'last_name': request.user.last_name,
                'email': request.user.email,
            }
            form = CommentForm(initial=initial_data)
        else:
            pass
    return render(request, 'firstblog/post/comment.html',
                  {'post':post,
                  'form':form,
                  'comment':comment})

def home(request):
    return render(request,'home/home.html')

def post_search(request):
    form = SearchForm()
    query = None
    results = []

    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', weight = 'A') + SearchVector('body', weight = 'B')
            search_query = SearchQuery(query)
            results = Post.published.annotate(
                similarity = TrigramSimilarity('title', query),
            ).filter(similarity__gte = 0.1).order_by('-similarity')
    return render(request,
                    'firstblog/post/search.html',
                    {'form': form,
                    'query': query,
                    'results': results})

my_blog/firstblog/templates/firstblog/base.html
{% load blog_tags %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">My Blog</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Contact</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container mt-5">
        <div class="row">
            <div class="col-md-8">
                <div class="card mb-4">
                    <img src="/media/blog.jpg" class="card-img-top" alt="...">
                    <div class="card-body">
                        {% block content %}
                        {% endblock %}  
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="p-4 mb-3 bg-light rounded">
                    <h4>About</h4>
                    <p class="mb-0">This is a blog about...
                        I've written {% total_posts %} posts so far.
                    </p>
                </div>
                <div class="p-4">
                    <p>
                        <a href="{% url "firstblog:post_feed" %}">
                            Subscribe to my RSS feed
                        </a>
                    </p>
                    <h3>Lastest posts</h3>
                    {% show_lastest_posts 3 %}
                    <h3>Most commented posts</h3>
                    {% get_most_commented_posts as most_commented_posts %}
                    <ul>
                        {% for post in most_commented_posts %}
                            <li>
                                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                    <h4>shopping</h4>
                    <div>
                        <img src="/media/shop.jpeg" class="img-thumbnail">
                    </div>
                    <ol class="list-unstyled mb-0">
                        <li><a href="{% url 'shop:product_list' %}">you can buy here anything you need</a></li>
                    </ol>
                </div>
                <div class="p-4">
                    <h4>learning</h4>
                    <div>
                        <img src="/media/learn.jpg" class="img-thumbnail">
                    </div>
                    <ol class="list-unstyled mb-0">
                        <li><a href="#">you can learn here anything you need</a></li>
                    </ol>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.min.js"></script>
</body>
</html>